// <auto-generated />
using System;
using Backend_POS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_POS.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Backend_POS.Models.Kupac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ADRESA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MJESTO")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NAZIV")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ŠIFRA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Kupac");
                });

            modelBuilder.Entity("Backend_POS.Models.Proizvod", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("CIJENA")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("JEDINICA_MJERE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NAZIV")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("STANJE")
                        .HasColumnType("int");

                    b.Property<string>("ŠIFRA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Proizvod");
                });

            modelBuilder.Entity("Backend_POS.Models.Stavke_racuna", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("CIJENA")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("IZNOS_POPUSTA")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("KOLICINA")
                        .HasColumnType("int");

                    b.Property<decimal>("POPUST")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProizvodID")
                        .HasColumnType("int");

                    b.Property<int?>("ProizvodID1")
                        .HasColumnType("int");

                    b.Property<decimal>("VRIJEDNOST")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Zaglavlje_racunaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProizvodID");

                    b.HasIndex("ProizvodID1");

                    b.HasIndex("Zaglavlje_racunaID");

                    b.ToTable("Stavke_racuna");
                });

            modelBuilder.Entity("Backend_POS.Models.Zaglavlje_racuna", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BROJ")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DATUM")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KupacID")
                        .HasColumnType("int");

                    b.Property<int?>("KupacID1")
                        .HasColumnType("int");

                    b.Property<string>("NAPOMENA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("KupacID");

                    b.HasIndex("KupacID1");

                    b.ToTable("Zaglavlje_racuna");
                });

            modelBuilder.Entity("Backend_POS.Models.Stavke_racuna", b =>
                {
                    b.HasOne("Backend_POS.Models.Proizvod", "Proizvod")
                        .WithMany()
                        .HasForeignKey("ProizvodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_POS.Models.Proizvod", null)
                        .WithMany("Stavke_racuna")
                        .HasForeignKey("ProizvodID1");

                    b.HasOne("Backend_POS.Models.Zaglavlje_racuna", "Zaglavlje_racuna")
                        .WithMany("Stavke_racuna")
                        .HasForeignKey("Zaglavlje_racunaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proizvod");

                    b.Navigation("Zaglavlje_racuna");
                });

            modelBuilder.Entity("Backend_POS.Models.Zaglavlje_racuna", b =>
                {
                    b.HasOne("Backend_POS.Models.Kupac", "Kupac")
                        .WithMany()
                        .HasForeignKey("KupacID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_POS.Models.Kupac", null)
                        .WithMany("Zaglavlje_racuna")
                        .HasForeignKey("KupacID1");

                    b.Navigation("Kupac");
                });

            modelBuilder.Entity("Backend_POS.Models.Kupac", b =>
                {
                    b.Navigation("Zaglavlje_racuna");
                });

            modelBuilder.Entity("Backend_POS.Models.Proizvod", b =>
                {
                    b.Navigation("Stavke_racuna");
                });

            modelBuilder.Entity("Backend_POS.Models.Zaglavlje_racuna", b =>
                {
                    b.Navigation("Stavke_racuna");
                });
#pragma warning restore 612, 618
        }
    }
}
